version: "3"
services:
  web:
    image: nginx:1.21.4-alpine
    command: nginx-debug -g 'daemon off;'
    volumes:
      - ./public:/public:ro
      - .docker/nginx.http.conf:/etc/nginx/conf.d/default.conf
    working_dir: /public
    depends_on:
      - app
    ports:
      - "8080:80"

    networks:
      - private
      - default

  app:
    image: decidim
    build: .
    environment:
      - DB_HOST=pg
      - DB_USER=postgres
      - DB_PASSWORD=my-insecure-pw
      - RAILS_ENV=production
      - RAILS_PORT=3000
      - RAILS_MAX_THREAD=5
      - SECRET_KEY_BASE=J9jEZgGFudNB4kEeqYHwoht4IQvinBhf
      - FROM_MAILER_ADDRESS=me@domain.org
      - APPLICATION_NAME=My application name
      - LOG_LEVEL=debug
      - ACTIVE_JOB_ADAPTER=delayed_job
    ports:
      - 3000:3000
    networks:
      - private
    depends_on:
      - pg

  pg:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=my-insecure-pw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=decidim
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - private

  redis:  
    image: redis

  mailer:  
    image: tophfr/mailcatcher
    ports:
      - "1025:1025"
      - "1080:80"

volumes:
  node_modules: {}
  pg-data: {}

networks:
  private:
    internal: true