# This docker-compose is for demonstration purpose only.
# Please changes credentials and user args for your production installation. 

version: "3"
services:
  app:
    image: decidim
    build:
      context: .
      args:
        # ===
        # Non-root user configurations
        # ===
        # Your home directory will be /home/ocsin/app
        USER: ocsin
        USER_UID: 1000
        GROUP: admin
        GROUP_UID: 1000
    env_file: .env
    ports:
      - 3000:3000
    networks:
      - default
      - private
    depends_on:
      - pg
      - redis

  pg:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=my-insecure-pw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=decidim
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - private

  redis:  
    image: redis:4-alpine
    command: redis-server --requirepass redis-insecure-password
    networks:
      - private

  mailer:  
    image: tophfr/mailcatcher
    ports:
      - "1025:1025"
      - "1080:80"

volumes:
  node_modules: {}
  pg-data: {}

networks:
  private:
    internal: true